blog/urls.py
from django.urls import path

from blog.views import post_details,filter_of_category

urlpatterns = [
    path('post/details/<int:post_id>', post_details, name='post-details'),
    path('post/category/<category_name>', filter_of_category, name='category-filter'),
]

wordify/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from blog.views import home,contact,about

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('contact', contact, name='contact'),
    path('about/<int:profile_id>', about, name='about'),
    path('blog/',include('blog.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    full_name = models.CharField(max_length=100)
    photo = models.ImageField()
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.full_name


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Post(models.Model):
    photo = models.ImageField()
    title = models.CharField(max_length=100)
    body = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True)
    create_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

blog/views.py
from django.http import HttpResponse
from django.shortcuts import render
from blog.custom_context import my_context
# Create your views here.
from blog.models import Post, Category, Profile


def home(request):
    posts = Post.objects.all()
    context = {
        'posts': posts
    }
    return render(request,'blog/home.html', context)


def post_details(request,post_id):
    try:
        post_obj = Post.objects.get(id = post_id)
        context = {
            'post': post_obj
        }
        return render(request,'blog/post_details.html',context)
    except Exception as err:
        print(err)
        return HttpResponse('404 Not Found')

def filter_of_category(request,category_name):
    category_obj = Category.objects.get(name=category_name)

    post_category = Post.objects.filter(category = category_obj)
    context = {'posts': post_category}
    return render(request,'blog/home.html',context)

def contact(request):
    return render(request,'blog/contact.html')

def about(request,profile_id):
    profile_obj = Profile.objects.get(id = profile_id)
    profile_post_filter = Post.objects.filter(author = profile_obj.user)
    context = {'profile': profile_obj, 'profile_filter': profile_post_filter}
    return render(request,'blog/about.html',context)

templates/base.html
{% load static %}
{% include 'partials/header.html' %}

    <div class="wrap">

      <header role="banner">
        {% include 'partials/header_top_banner.html' %}

        {% include 'partials/header_navbar.html' %}
      </header>
      <!-- END header -->
      {% include 'partials/header_slider.html'%}
      <!-- END section -->

      <section class="site-section py-sm">
        <div class="container">

          <div class="row blog-entries">
            <div class="col-md-12 col-lg-8 main-content">
              {% block content %}

              {% endblock %}
            </div>
            <!-- END main-content -->

          {% include 'partials/sidebar.html' %}
            <!-- END sidebar -->

          </div>
        </div>
      </section>
    
      {% include 'partials/footer.html' %}
      <!-- END footer -->
    </div>
    <!-- loader -->
  {% include 'partials/js.html' %}

templates/blog/about.html
{% extends 'base.html' %}

{% block content %}

<section class="site-section pt-5">
      <div class="container">

        <div class="row blog-entries">
          <div class="col-md-12 col-lg-12 main-content">

            <div class="row">
              <div class="col-md-12">
                <h2 class="mb-4">{{ profile.full_name }}</h2>
                <p class="mb-5"><img src="{{ profile.photo.url }}" alt="Image placeholder" class="img-fluid"></p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum minima eveniet recusandae suscipit eum laboriosam fugit amet deleniti iste et. Ad dolores, necessitatibus non saepe tenetur impedit commodi quibusdam natus repellat, exercitationem accusantium perferendis officiis. Laboriosam impedit quia minus pariatur!</p>
                <p>Dignissimos iste consectetur, nemo magnam nulla suscipit eius quibusdam, quo aperiam quia quae est explicabo nostrum ab aliquid vitae obcaecati tenetur beatae animi fugiat officia id ipsam sint? Obcaecati ea nisi fugit assumenda error totam molestiae saepe fugiat officiis quam?</p>
                <p>Culpa porro quod doloribus dolore sint. Distinctio facilis ullam voluptas nemo voluptatum saepe repudiandae adipisci officiis, explicabo eaque itaque sed necessitatibus, fuga, ea eius et aliquam dignissimos repellendus impedit pariatur voluptates. Dicta perferendis assumenda, nihil placeat, illum quibusdam. Vel, incidunt?</p>
                <p>Dolorum blanditiis illum quo quaerat, possimus praesentium perferendis! Quod autem optio nobis, placeat officiis dolorem praesentium odit. Vel, cum, a. Adipisci eligendi eaque laudantium dicta tenetur quod, pariatur sunt sed natus officia fuga accusamus reprehenderit ratione, provident possimus ut voluptatum.</p>
              </div>
            </div>

            <div class="row mb-5 mt-5">
              <div class="col-md-12 mb-5">
                <h2>My Latest Posts</h2>
              </div>
              <div class="col-md-12">
                  {% for post in profile_filter %}
                <div class="post-entry-horzontal">
                  <a href="{% url 'post-details' post.id %}">
                    <div class="image" style="background-image: url({{ post.photo.url }});"></div>
                    <span class="text">
                      <div class="post-meta">
                        <span class="author mr-2"><img src="{{ post.author.profile.photo.url }}" alt="Colorlib"> {{ post.author.profile.full_name }}</span>&bullet;
                        <span class="mr-2">{{ post.create_on }} </span> &bullet;
                        <span class="ml-2"><span class="fa fa-comments"></span> 3</span>
                      </div>
                      <h2>{{ post.title }}</h2>
                    </span>
                  </a>
                </div>
                  {% endfor %}
                <!-- END post -->


              </div>
            </div>

            <div class="row">
              <div class="col-md-12 text-center">
                <nav aria-label="Page navigation" class="text-center">
                  <ul class="pagination">
                      <li class="page-item  active"><a class="page-link" href="#">&lt;</a></li>
                      <li class="page-item"><a class="page-link" href="#">1</a></li>
                      <li class="page-item"><a class="page-link" href="#">2</a></li>
                      <li class="page-item"><a class="page-link" href="#">3</a></li>
                      <li class="page-item"><a class="page-link" href="#">4</a></li>
                      <li class="page-item"><a class="page-link" href="#">5</a></li>
                      <li class="page-item"><a class="page-link" href="#">&gt;</a></li>
                    </ul>
                </nav>
              </div>
            </div>



          </div>

          <!-- END main-content -->


        </div>
      </div>
    </section>

{% endblock %}

templates/blog/contact.html
{% extends 'base.html' %}

{% block content %}

<section class="site-section">
      <div class="container">
        <div class="row mb-4">
          <div class="col-md-6">
            <h1>Contact Me</h1>
          </div>
        </div>
        <div class="row blog-entries">
          <div class="col-md-12 col-lg-12 main-content">

            <form action="#" method="post">
                  <div class="row">
                    <div class="col-md-12 form-group">
                      <label for="name">Name</label>
                      <input type="text" id="name" class="form-control ">
                    </div>
                    <div class="col-md-12 form-group">
                      <label for="phone">Phone</label>
                      <input type="text" id="phone" class="form-control ">
                    </div>
                    <div class="col-md-12 form-group">
                      <label for="email">Email</label>
                      <input type="email" id="email" class="form-control ">
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-12 form-group">
                      <label for="message">Write Message</label>
                      <textarea name="message" id="message" class="form-control " cols="30" rows="8"></textarea>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-6 form-group">
                      <input type="submit" value="Send Message" class="btn btn-primary">
                    </div>
                  </div>
                </form>


          </div>

          <!-- END main-content -->


          <!-- END sidebar -->

        </div>
      </div>
    </section>

{% endblock %}

templates/blog/home.html
{% extends 'base.html' %}
{% block content %}
  <div class="row">
    <div class="col-md-6">
      <h2 class="mb-4">Latest Posts</h2>
    </div>
  </div>


<div class="row">
  {% for post in posts %}
    <div class="col-md-6">
      <a href="{% url 'post-details' post.id %}" class="blog-entry element-animate" data-animate-effect="fadeIn">
        <img src="{{ post.photo.url }}" alt="Image placeholder">
        <div class="blog-content-body">
          <div class="post-meta">
            <span class="author mr-2"><img src="{{ post.author.profile.photo.url }}" alt="User"> {{ post.author }}</span>&bullet;
            <span class="mr-2">{{ post.create_on }} </span> &bullet;
            <span class="ml-2"><span class="fa fa-comments"></span> 3</span>
          </div>
          <h2>{{ post.title }}/h2>
        </div>
      </a>
    </div>
  {% endfor %}
</div>

<div class="row mt-5">
  <div class="col-md-12 text-center">
    <nav aria-label="Page navigation" class="text-center">
      <ul class="pagination">
        <li class="page-item  active"><a class="page-link" href="#">&lt;</a></li>
        <li class="page-item"><a class="page-link" href="#">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
        <li class="page-item"><a class="page-link" href="#">4</a></li>
        <li class="page-item"><a class="page-link" href="#">5</a></li>
        <li class="page-item"><a class="page-link" href="#">&gt;</a></li>
      </ul>
    </nav>
  </div>
</div>





{% endblock %}

templates/blog/post_details.html
{% extends 'base.html' %}
{% block content %}

<img src="{{ post.photo.url }}" alt="Image" class="img-fluid mb-5">

 <div class="post-meta">
    <span class="author mr-2"><img src="{{ post.author.profile.photo.url }}" alt="User" class="mr-2"> {{ post.author }}</span>&bullet;
    <span class="mr-2">{{ post.create_on }} </span> &bullet;
    <span class="ml-2"><span class="fa fa-comments"></span> 3</span>
 </div>
<h1 class="mb-4">{{ post.title }}</h1>

<a class="category mb-5" href="{% url 'category-filter' post.category.name %}">{{ post.category }}</a>

<div class="post-content-body">
    <p>{{ post.body }}</p>
</div>

{% endblock %}

templates/partials/footer.html
{% load static %}
<footer class="site-footer">
    <div class="container">
      <div class="row mb-5">
        <div class="col-md-4">
          <h3>About Us</h3>
          <p class="mb-4">
            <img src="{% static 'images/img_1.jpg' %}" alt="Image placeholder" class="img-fluid">
          </p>

          <p>Lorem ipsum dolor sit amet sa ksal sk sa, consectetur adipisicing elit. Ipsa harum inventore reiciendis. <a href="#">Read More</a></p>
        </div>
        <div class="col-md-6 ml-auto">
          <div class="row">
            <div class="col-md-7">
              <h3>Latest Post</h3>
              <div class="post-entry-sidebar">
                <ul>
                  <li>
                    <a href="">
                      <img src="{% static 'images/img_6.jpg' %}" alt="Image placeholder" class="mr-4">
                      <div class="text">
                        <h4>How to Find the Video Games of Your Youth</h4>
                        <div class="post-meta">
                          <span class="mr-2">March 15, 2018 </span> &bullet;
                          <span class="ml-2"><span class="fa fa-comments"></span> 3</span>
                        </div>
                      </div>
                    </a>
                  </li>
                  <li>
                    <a href="">
                      <img src="{% static 'images/img_3.jpg' %}" alt="Image placeholder" class="mr-4">
                      <div class="text">
                        <h4>How to Find the Video Games of Your Youth</h4>
                        <div class="post-meta">
                          <span class="mr-2">March 15, 2018 </span> &bullet;
                          <span class="ml-2"><span class="fa fa-comments"></span> 3</span>
                        </div>
                      </div>
                    </a>
                  </li>
                  <li>
                    <a href="">
                      <img src="{% static 'images/img_4.jpg' %}" alt="Image placeholder" class="mr-4">
                      <div class="text">
                        <h4>How to Find the Video Games of Your Youth</h4>
                        <div class="post-meta">
                          <span class="mr-2">March 15, 2018 </span> &bullet;
                          <span class="ml-2"><span class="fa fa-comments"></span> 3</span>
                        </div>
                      </div>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="col-md-1"></div>

            <div class="col-md-4">

              <div class="mb-5">
                <h3>Quick Links</h3>
                <ul class="list-unstyled">
                  <li><a href="#">About Us</a></li>
                  <li><a href="#">Travel</a></li>
                  <li><a href="#">Adventure</a></li>
                  <li><a href="#">Courses</a></li>
                  <li><a href="#">Categories</a></li>
                </ul>
              </div>

              <div class="mb-5">
                <h3>Social</h3>
                <ul class="list-unstyled footer-social">
                  <li><a href="#"><span class="fa fa-twitter"></span> Twitter</a></li>
                  <li><a href="#"><span class="fa fa-facebook"></span> Facebook</a></li>
                  <li><a href="#"><span class="fa fa-instagram"></span> Instagram</a></li>
                  <li><a href="#"><span class="fa fa-vimeo"></span> Vimeo</a></li>
                  <li><a href="#"><span class="fa fa-youtube-play"></span> Youtube</a></li>
                  <li><a href="#"><span class="fa fa-snapchat"></span> Snapshot</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 text-center">
          <p class="small">
        </p>
        </div>
      </div>
    </div>
</footer>

templates/partials/header.html
<!doctype html>
<html lang="en">
{% load static %}
  <head>
    <title>Colorlib Wordify &mdash; Minimal Blog Template</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300, 400,700|Inconsolata:400,700" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">

    <link rel="stylesheet" href="{% static 'fonts/ionicons/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/fontawesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">

    <!-- Theme Style -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body>

templates/partials/header_navbar.html
<nav class="navbar navbar-expand-md  navbar-light bg-light">
  <div class="container">


    <div class="collapse navbar-collapse" id="navbarMenu">
      <ul class="navbar-nav mx-auto">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="category.html" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
          <div class="dropdown-menu" aria-labelledby="dropdown05">
            {% for category in categoris %}
            <a class="dropdown-item" href="{% url 'category-filter' category.name %}">{{ category.name }}</a>
            {% endfor %}
          </div>
        </li>
        <li class="nav-item">

        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contact' %}">Contact</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/partials/header_slider.html
{% load static %}
<section class="site-section pt-5 pb-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">

          <div class="owl-carousel owl-theme home-slider">
            <div>
              <a href="blog-single.html" class="a-block d-flex align-items-center height-lg" style="background-image: url('{% static 'images/img_1.jpg' %}'); ">
                <div class="text half-to-full">
                  <span class="category mb-5">Food</span>
                  <div class="post-meta">

                    <span class="author mr-2"><img src="{% static 'images/person_1.jpg' %}" alt="Colorlib"> Colorlib</span>&bullet;
                    <span class="mr-2">March 15, 2018 </span> &bullet;
                    <span class="ml-2"><span class="fa fa-comments"></span> 3</span>

                  </div>
                  <h3>How to Find the Video Games of Your Youth</h3>
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem nobis, ut dicta eaque ipsa laudantium!</p>
                </div>
              </a>
            </div>
            <div>
              <a href="blog-single.html" class="a-block d-flex align-items-center height-lg" style="background-image: url('{% static 'images/img_2.jpg' %}'); ">
                <div class="text half-to-full">
                  <span class="category mb-5">Travel</span>
                  <div class="post-meta">

                    <span class="author mr-2"><img src="{% static 'images/person_1.jpg' %}" alt="Colorlib"> Colorlib</span>&bullet;
                    <span class="mr-2">March 15, 2018 </span> &bullet;
                    <span class="ml-2"><span class="fa fa-comments"></span> 3</span>

                  </div>
                  <h3>How to Find the Video Games of Your Youth</h3>
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem nobis, ut dicta eaque ipsa laudantium!</p>
                </div>
              </a>
            </div>
            <div>
              <a href="blog-single.html" class="a-block d-flex align-items-center height-lg" style="background-image: url('{% static 'images/img_3.jpg' %}'); ">
                <div class="text half-to-full">
                  <span class="category mb-5">Sports</span>
                  <div class="post-meta">

                    <span class="author mr-2"><img src="{% static 'images/person_1.jpg' %}" alt="Colorlib"> Colorlib</span>&bullet;
                    <span class="mr-2">March 15, 2018 </span> &bullet;
                    <span class="ml-2"><span class="fa fa-comments"></span> 3</span>

                  </div>
                  <h3>How to Find the Video Games of Your Youth</h3>
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem nobis, ut dicta eaque ipsa laudantium!</p>
                </div>
              </a>
            </div>
          </div>

        </div>
      </div>

    </div>


    </section>

templates/partials/header_top_banner.html
<div class="top-bar">
  <div class="container">
    <div class="row">
      <div class="col-9 social">
        <a href="#"><span class="fa fa-twitter"></span></a>
        <a href="#"><span class="fa fa-facebook"></span></a>
        <a href="#"><span class="fa fa-instagram"></span></a>
        <a href="#"><span class="fa fa-youtube-play"></span></a>
      </div>
      <div class="col-3 search-top">
        <!-- <a href="#"><span class="fa fa-search"></span></a> -->
        <form action="#" class="search-top-form">
          <span class="icon fa fa-search"></span>
          <input type="text" id="s" placeholder="Type keyword to search...">
        </form>
      </div>
    </div>
  </div>
</div>

<div class="container logo-wrap">
  <div class="row pt-5">
    <div class="col-12 text-center">
      <a class="absolute-toggle d-block d-md-none" data-toggle="collapse" href="#navbarMenu" role="button" aria-expanded="false" aria-controls="navbarMenu"><span class="burger-lines"></span></a>
      <h1 class="site-logo"><a href="index.html">Wordify</a></h1>
    </div>
  </div>
</div>

templates/partials/js.html
{% load static %}

<div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#f4b214"/></svg></div>

<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.0.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>


<script src="{% static 'js/main.js' %}"></script>
  </body>
</html>

templates/partials/sidebar.html
{% load static %}
<div class="col-md-12 col-lg-4 sidebar">
  <div class="sidebar-box search-form-wrap">
    <form action="#" class="search-form">
      <div class="form-group">
        <span class="icon fa fa-search"></span>
        <input type="text" class="form-control" id="s" placeholder="Type a keyword and hit enter">
      </div>
    </form>
  </div>
  <!-- END sidebar-box -->
  <div class="sidebar-box">
    <div class="bio text-center">
      <img src="{% static 'images/person_1.jpg' %}" alt="Image Placeholder" class="img-fluid">
      <div class="bio-body">
        <h2>David Craig</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem facilis sunt repellendus excepturi beatae porro debitis voluptate nulla quo veniam fuga sit molestias minus.</p>
        <p><a href="#" class="btn btn-primary btn-sm rounded">Read my bio</a></p>
        <p class="social">
          <a href="#" class="p-2"><span class="fa fa-facebook"></span></a>
          <a href="#" class="p-2"><span class="fa fa-twitter"></span></a>
          <a href="#" class="p-2"><span class="fa fa-instagram"></span></a>
          <a href="#" class="p-2"><span class="fa fa-youtube-play"></span></a>
        </p>
      </div>
    </div>
  </div>
  <!-- END sidebar-box -->
  <div class="sidebar-box">
    <h3 class="heading">Latest Post</h3>
    <div class="post-entry-sidebar">
      <ul>
        {% for latest in latest_post %}
        <li>
          <a href="{% url 'post-details' latest.id %}">
            <img src="{{ latest.photo.url }}" alt="Image placeholder" class="mr-4">
            <div class="text">
              <h4>{{ latest.title }}</h4>
              <div class="post-meta">
                <span class="mr-2">{{ latest.create_on }} </span>
              </div>
            </div>
          </a>
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>
  <!-- END sidebar-box -->

  <div class="sidebar-box">
    <h3 class="heading">Categories</h3>
    <ul class="categories">
      {% for category in categoris %}
      <li><a href="{% url 'category-filter' category.name %}">{{ category.name }} <span>({{ category.post_set.count }})</span></a></li>
      {% endfor %}
    </ul>
  </div>
  <!-- END sidebar-box -->
</div>